name: Android Debug CI

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Set up Token
        run: |
          echo "github_username=${{ secrets.USER_NAME }}" >> $GITHUB_ENV
          echo "github_access_token=${{ secrets.CORE_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Android Debug Build
        run: ./gradlew :app:assembleDebug
      - name: Android LintCheck
        run: ./gradlew detekt
      - name : Android Test
        run: ./gradlew testAll

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: android-tw
          fields: author,commit,job,took,pullRequest # action,eventName,ref,workflow,job,took 추가할 수 있음
          mention: here
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: TW-Artifacts-${{ github.run_number }}
          path: |
            app/build/outputs/apk/debug
          retention-days: 1